"""
train_diagnostic_models.py

Direct-run two-stage training script for the V3 high-speed PCB
signal-integrity diagnostic dataset.

Designed for the V3 dataset generated by:
- generate_training_dataset.py
- build_training_database.py

V3 concept:
Stage 1: baseline/global deviation detection
    - deviation from theoretical target
    - deviation from PN / lot population baseline
    - output: normal / warning / out_of_spec / severe

Stage 2: shape-based abnormality diagnosis
    - TDR local spike/dip/area/width
    - S21 notch / ripple
    - return-loss and high-frequency loss shape
    - output: likely root-cause class

Default workflow:
1. Load view_two_stage_summary from SQLite if available.
2. Train Stage 1 status heads:
   - stage1_overall_status
   - stage1_impedance_status
   - stage1_loss_status
3. Train Stage 2 root-cause classifier using shape-aware features.
4. Evaluate by random split and PN holdout split.
5. Save metrics, classification reports, confusion matrices,
   feature importances, best model pickles, and a two-stage model bundle.

This is a direct-run version. You can press Run in VS Code.
Change parameters in the USER SETTINGS section below.
"""

from __future__ import annotations

import pickle
import sqlite3
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


# ============================================================
# USER SETTINGS
# ============================================================

DATASET_DIR = "si_simulated_dataset_v3"
DB_NAME = "si_simulated_dataset_v3.sqlite"
DB_NAME_CANDIDATES = [
    "si_simulated_dataset_v3.sqlite",
    "si_simulated_dataset.sqlite",
    "si_v3_test.sqlite",
]

# Source options: "auto", "sqlite", "csv"
SOURCE = "auto"

AUTO_FIND_DATASET = True
DATASET_FALLBACKS = [
    "si_simulated_dataset_v3",
    "si_simulated_dataset",
    "si_v3_test",
]

# Leave None to use DATASET_DIR/outputs/model_training_v3_two_stage
OUTPUT_DIR = None

SEED = 42
HOLDOUT_PN = "PN06"
INCLUDE_GOLDEN = False

RUN_RANDOM_SPLIT = True
RUN_PN_HOLDOUT = True

# Stage-1 heads. Missing columns are skipped automatically.
STAGE1_TARGETS = [
    "stage1_overall_status",
    "stage1_impedance_status",
    "stage1_loss_status",
]

# If True, Stage 2 is trained only on cases that Stage 1 says are not normal.
# Keep False by default so the root-cause model also learns normal_production.
STAGE2_ONLY_STAGE1_NON_NORMAL = False

# To speed up quick tests, set e.g. 2000. Leave None for full dataset.
MAX_ROWS_FOR_DEBUG = None

# Minimum samples per class retained for a task.
MIN_CLASS_COUNT = 5


# ============================================================
# Label definitions
# ============================================================

STAGE1_STATUS_ORDER = [
    "normal",
    "warning",
    "out_of_spec",
    "severe",
]

STAGE1_DISPLAY_LABELS = {
    "normal": "Normal",
    "warning": "Warning",
    "out_of_spec": "Out-of-spec",
    "severe": "Severe",
}

STAGE2_LABEL_ORDER = [
    "normal_production",
    "roughness_high",
    "high_df",
    "width_variation",
    "local_defect",
    "via_stub",
    "return_path_issue",
]

STAGE2_DISPLAY_LABELS = {
    "normal_production": "Normal",
    "roughness_high": "Roughness",
    "high_df": "High Df",
    "width_variation": "Width",
    "local_defect": "Local defect",
    "via_stub": "Via stub",
    "return_path_issue": "Return path",
}


# ============================================================
# Column rules
# ============================================================

IDENTIFIER_AND_TARGET_COLUMNS = {
    "case_id",
    "em_case_id",
    "source_case_id",
    "PN_ID",
    "label",
    "expected_label",
    "expected_group",
    "predicted_label",
    "split",
    "stage1_impedance_status",
    "stage1_loss_status",
    "stage1_overall_status",
    "impedance_mean_risk",
    "impedance_local_risk",
    "loss_baseline_risk",
}

# Metadata / hidden simulation parameters that should NOT be used as model inputs.
# They are useful for analysis, but using them would leak the synthetic ground truth.
HIDDEN_METADATA_COLUMNS = {
    "severity",
    "defect_type",
    "line_type",
    "Dk",
    "Df",
    "roughness_um",
    "trace_width_um",
    "copper_thickness_um",
    "dielectric_thickness_factor",
    "width_change_pct",
    "defect_length_mm",
    "defect_position_mm",
    "stub_length_mm",
    "return_path_extra_L_pH",
    "Dk_nominal",
    "Df_nominal",
    "roughness_nominal_um",
    "trace_width_nominal_um",
    "copper_thickness_nominal_um",
    "short_coupon_mm",
    "long_coupon_mm",
}

# Risk-score columns are deterministic rule outputs used to produce Stage-1 status.
# Exclude them from Stage-1 inputs to avoid a trivial rule-leakage model.
RISK_SCORE_COLUMNS = {
    "impedance_mean_risk_score",
    "impedance_local_risk_score",
    "loss_baseline_risk_score",
    "stage1_overall_risk_score",
}

STAGE1_EXCLUDE_COLUMNS = (
    IDENTIFIER_AND_TARGET_COLUMNS
    | HIDDEN_METADATA_COLUMNS
    | RISK_SCORE_COLUMNS
)

STAGE2_EXCLUDE_COLUMNS = (
    IDENTIFIER_AND_TARGET_COLUMNS
    | HIDDEN_METADATA_COLUMNS
    | RISK_SCORE_COLUMNS
)


def is_stage1_feature_name(col: str) -> bool:
    """Features for global / baseline deviation detection."""
    if col in STAGE1_EXCLUDE_COLUMNS:
        return False

    include_tokens = [
        "target_dev",
        "theory_dev",
        "theory_excess_ratio",
        "pn_baseline_dev",
        "pn_robust_z",
        "pn_excess_ratio",
        "loss_baseline_excess_ratio",
    ]
    if any(token in col for token in include_tokens):
        return True

    # Raw measured global features are also allowed.
    if col.startswith(("IL_", "DeltaL_")):
        return True
    if col in {
        "Z_mean",
        "Z_max_dev",
        "TDR_peak_abs_ohm",
        "TDR_energy",
        "RL_min",
        "RL_mean",
        "RL_ripple",
    }:
        return True

    return False


def is_stage2_feature_name(col: str) -> bool:
    """Features for shape/root-cause diagnosis."""
    if col in STAGE2_EXCLUDE_COLUMNS:
        return False

    shape_prefixes = (
        "TDR_",
        "RL_",
        "notch_",
        "S21_ripple",
        "IL_",
        "DeltaL_",
        "Z_",
    )
    if col.startswith(shape_prefixes):
        return True

    shape_tokens = [
        "ripple",
        "slope",
        "peak",
        "dip",
        "energy",
        "local",
        "region",
        "baseline_dev",
        "robust_z",
    ]
    if any(token in col for token in shape_tokens):
        return True

    return False


# ============================================================
# SQLite / CSV loading
# ============================================================


def resolve_dataset_dir() -> Path:
    dataset_dir = Path(DATASET_DIR)
    if dataset_dir.exists():
        return dataset_dir

    if AUTO_FIND_DATASET:
        for candidate in DATASET_FALLBACKS:
            path = Path(candidate)
            if path.exists():
                return path

    raise FileNotFoundError(
        "Dataset directory not found.\n"
        f"Current DATASET_DIR = {DATASET_DIR!r}\n"
        "Please change DATASET_DIR in the USER SETTINGS section."
    )


def table_or_view_exists(conn: sqlite3.Connection, name: str) -> bool:
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE name=? AND type IN ('table', 'view');",
        (name,),
    ).fetchone()
    return row is not None


def resolve_data_source(dataset_dir: Path) -> Tuple[str, Optional[Path]]:
    if SOURCE == "csv":
        return "csv", None

    candidates: List[Path] = []
    if DB_NAME:
        candidates.append(dataset_dir / DB_NAME)
    for name in DB_NAME_CANDIDATES:
        path = dataset_dir / name
        if path not in candidates:
            candidates.append(path)
    candidates.extend(sorted(dataset_dir.glob("*.sqlite")))

    for db_path in candidates:
        if db_path.exists():
            if SOURCE in {"auto", "sqlite"}:
                return "sqlite", db_path

    if SOURCE == "sqlite":
        names = ", ".join(str(p) for p in candidates)
        raise FileNotFoundError(f"No SQLite DB found. Tried: {names}")

    return "csv", None


def read_sqlite_v3(db_path: Path) -> pd.DataFrame:
    with sqlite3.connect(db_path) as conn:
        if table_or_view_exists(conn, "view_two_stage_summary"):
            return pd.read_sql_query("SELECT * FROM view_two_stage_summary", conn)

        if not table_or_view_exists(conn, "si_fingerprint_features"):
            raise ValueError(f"SQLite DB missing si_fingerprint_features: {db_path}")

        base = pd.read_sql_query("SELECT * FROM si_fingerprint_features", conn)
        for table in ["si_stage1_deviation_features", "si_stage2_shape_features"]:
            if table_or_view_exists(conn, table):
                extra = pd.read_sql_query(f"SELECT * FROM {table}", conn)
                base = merge_without_duplicate_columns(base, extra, key="case_id")
        return base


def merge_without_duplicate_columns(left: pd.DataFrame, right: pd.DataFrame, key: str) -> pd.DataFrame:
    keep_cols = [key] + [c for c in right.columns if c != key and c not in left.columns]
    return left.merge(right[keep_cols], on=key, how="left")


def read_csv_v3(dataset_dir: Path) -> pd.DataFrame:
    feature_path = dataset_dir / "processed" / "si_fingerprint_features.csv"
    if not feature_path.exists():
        raise FileNotFoundError(f"Missing feature CSV: {feature_path}")

    df = pd.read_csv(feature_path)
    for csv_name in [
        "si_stage1_deviation_features.csv",
        "si_stage2_shape_features.csv",
    ]:
        path = dataset_dir / "processed" / csv_name
        if path.exists():
            extra = pd.read_csv(path)
            df = merge_without_duplicate_columns(df, extra, key="case_id")
    return df


def load_v3_dataframe(dataset_dir: Path) -> Tuple[pd.DataFrame, str]:
    source, db_path = resolve_data_source(dataset_dir)
    if source == "sqlite":
        assert db_path is not None
        return read_sqlite_v3(db_path), f"sqlite: {db_path}"
    return read_csv_v3(dataset_dir), f"csv: {dataset_dir / 'processed'}"


# ============================================================
# Feature selection and data preparation
# ============================================================


def is_numeric_like(series: pd.Series) -> bool:
    if pd.api.types.is_numeric_dtype(series):
        return True
    converted = pd.to_numeric(series, errors="coerce")
    return converted.notna().mean() > 0.95


def select_feature_columns(df: pd.DataFrame, selector) -> List[str]:
    cols: List[str] = []
    for c in df.columns:
        if not selector(c):
            continue
        if is_numeric_like(df[c]):
            cols.append(c)
    return sorted(cols)


def clean_task_dataframe(
    df: pd.DataFrame,
    target_col: str,
    include_golden: bool,
    seed: int,
) -> pd.DataFrame:
    if target_col not in df.columns:
        raise ValueError(f"Missing target column: {target_col}")
    if "PN_ID" not in df.columns:
        raise ValueError("Data must include PN_ID.")

    data = df.copy()
    if not include_golden and "label" in data.columns:
        data = data[data["label"] != "golden_normal"].copy()

    data = data.dropna(subset=[target_col, "PN_ID"]).copy()
    data[target_col] = data[target_col].astype(str)

    # Drop rare target classes that cannot be split reliably.
    counts = data[target_col].value_counts()
    valid = counts[counts >= MIN_CLASS_COUNT].index.tolist()
    data = data[data[target_col].isin(valid)].copy()

    if MAX_ROWS_FOR_DEBUG is not None and len(data) > MAX_ROWS_FOR_DEBUG:
        classes = data[target_col].nunique()
        per_class = max(1, MAX_ROWS_FOR_DEBUG // max(classes, 1))
        data = (
            data.groupby(target_col, group_keys=False)
            .apply(lambda x: x.sample(min(len(x), per_class), random_state=seed))
            .reset_index(drop=True)
        )

    return data


def convert_features_to_numeric(df: pd.DataFrame, feature_cols: List[str]) -> Tuple[pd.DataFrame, List[str]]:
    data = df.copy()
    for c in feature_cols:
        data[c] = pd.to_numeric(data[c], errors="coerce")

    usable = [c for c in feature_cols if not data[c].isna().all()]
    dropped = [c for c in feature_cols if c not in usable]
    if dropped:
        print(f"[WARN] Dropped all-NaN features ({len(dropped)}): {dropped[:20]}{' ...' if len(dropped) > 20 else ''}")
    if not usable:
        raise ValueError("No usable numeric feature columns after conversion.")
    return data, usable


def summarize_feature_groups(feature_cols: List[str]) -> pd.DataFrame:
    rows = []
    for c in feature_cols:
        if "robust_z" in c:
            group = "pn_robust_z"
        elif "baseline_dev" in c:
            group = "pn_baseline_dev"
        elif "theory" in c:
            group = "theory_deviation"
        elif c.startswith("IL_slope"):
            group = "IL_slope"
        elif c.startswith("IL_"):
            group = "IL_frequency"
        elif c.startswith("DeltaL_slope"):
            group = "DeltaL_slope"
        elif c.startswith("DeltaL_"):
            group = "DeltaL_frequency"
        elif c.startswith("RL_"):
            group = "return_loss"
        elif c.startswith("Z_") or c.startswith("TDR_"):
            group = "TDR_impedance"
        elif c.startswith("notch_") or c.startswith("S21_ripple"):
            group = "notch_ripple"
        else:
            group = "other"
        rows.append({"feature": c, "group": group})
    return pd.DataFrame(rows)


# ============================================================
# Model definitions
# ============================================================


def build_models(seed: int) -> Dict[str, object]:
    return {
        "logistic_regression": LogisticRegression(
            max_iter=4000,
            class_weight="balanced",
            solver="lbfgs",
            random_state=seed,
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=500,
            max_depth=None,
            min_samples_leaf=2,
            class_weight="balanced",
            n_jobs=-1,
            random_state=seed,
        ),
        "hist_gradient_boosting": HistGradientBoostingClassifier(
            max_iter=300,
            learning_rate=0.06,
            max_leaf_nodes=31,
            random_state=seed,
        ),
    }


def make_pipeline(estimator: object, feature_cols: List[str], scale: bool) -> Pipeline:
    num_steps = [("imputer", SimpleImputer(strategy="median"))]
    if scale:
        num_steps.append(("scaler", StandardScaler()))

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", Pipeline(num_steps), feature_cols),
        ],
        remainder="drop",
    )

    return Pipeline([
        ("preprocess", preprocessor),
        ("model", estimator),
    ])


# ============================================================
# Splits / evaluation / plots
# ============================================================


def random_split_dataframe(df: pd.DataFrame, target_col: str, seed: int) -> Tuple[pd.DataFrame, pd.DataFrame]:
    y = df[target_col]
    counts = y.value_counts()
    stratify = y if len(counts) > 1 and counts.min() >= 2 else None
    train_df, test_df = train_test_split(
        df,
        test_size=0.20,
        random_state=seed,
        stratify=stratify,
    )
    return train_df.copy(), test_df.copy()


def pn_holdout_split_dataframe(df: pd.DataFrame, target_col: str, holdout_pn: str) -> Tuple[pd.DataFrame, pd.DataFrame]:
    train_df = df[df["PN_ID"] != holdout_pn].copy()
    test_df = df[df["PN_ID"] == holdout_pn].copy()

    if train_df.empty or test_df.empty:
        raise ValueError(f"Invalid holdout PN: {holdout_pn}. Train or test set is empty.")

    common_targets = sorted(set(train_df[target_col]).intersection(set(test_df[target_col])))
    train_df = train_df[train_df[target_col].isin(common_targets)].copy()
    test_df = test_df[test_df[target_col].isin(common_targets)].copy()

    # Keep only classes with enough samples in both train and test.
    train_counts = train_df[target_col].value_counts()
    test_counts = test_df[target_col].value_counts()
    valid = [
        c for c in common_targets
        if train_counts.get(c, 0) >= MIN_CLASS_COUNT and test_counts.get(c, 0) >= 1
    ]
    train_df = train_df[train_df[target_col].isin(valid)].copy()
    test_df = test_df[test_df[target_col].isin(valid)].copy()

    if train_df.empty or test_df.empty:
        raise ValueError(f"No common valid target classes between training set and holdout PN: {holdout_pn}")

    return train_df, test_df


def resolve_labels(y_true: pd.Series, y_pred: np.ndarray, preferred_order: List[str]) -> List[str]:
    present = set(y_true.astype(str).unique()).union(set(pd.Series(y_pred).astype(str).unique()))
    labels = [x for x in preferred_order if x in present]
    labels += sorted([x for x in present if x not in labels])
    return labels


def evaluate_model(
    name: str,
    model: Pipeline,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    preferred_label_order: List[str],
) -> Tuple[Dict, pd.DataFrame, np.ndarray, List[str]]:
    y_pred = model.predict(X_test)
    labels = resolve_labels(y_test, y_pred, preferred_label_order)

    metrics = {
        "model": name,
        "accuracy": accuracy_score(y_test, y_pred),
        "macro_f1": f1_score(y_test, y_pred, average="macro", zero_division=0),
        "weighted_f1": f1_score(y_test, y_pred, average="weighted", zero_division=0),
        "test_samples": len(y_test),
        "class_count_test": y_test.nunique(),
    }

    report_dict = classification_report(
        y_test,
        y_pred,
        labels=labels,
        output_dict=True,
        zero_division=0,
    )
    report_df = pd.DataFrame(report_dict).T.reset_index().rename(columns={"index": "class"})
    cm = confusion_matrix(y_test, y_pred, labels=labels)
    return metrics, report_df, cm, labels


def plot_confusion_matrix(
    cm: np.ndarray,
    labels: List[str],
    title: str,
    out_path: Path,
    display_label_map: Dict[str, str],
) -> None:
    display_labels = [display_label_map.get(l, l) for l in labels]
    fig, ax = plt.subplots(figsize=(max(7, len(labels) * 1.2), max(6, len(labels) * 1.0)))
    im = ax.imshow(cm, interpolation="nearest")
    ax.set_title(title)
    fig.colorbar(im, ax=ax)

    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(display_labels, rotation=35, ha="right")
    ax.set_yticklabels(display_labels)
    ax.set_ylabel("True label")
    ax.set_xlabel("Predicted label")

    threshold = cm.max() / 2 if cm.size and cm.max() > 0 else 0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(
                j,
                i,
                format(int(cm[i, j]), "d"),
                ha="center",
                va="center",
                color="white" if cm[i, j] > threshold else "black",
                fontsize=9,
            )

    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    print(f"[SAVED] {out_path}")


def extract_feature_importance(model: Pipeline, feature_cols: List[str]) -> Optional[pd.DataFrame]:
    clf = model.named_steps["model"]
    if hasattr(clf, "feature_importances_"):
        importance = clf.feature_importances_
    elif hasattr(clf, "coef_"):
        coef = clf.coef_
        importance = np.mean(np.abs(coef), axis=0)
    else:
        return None

    if len(importance) != len(feature_cols):
        return None

    out = pd.DataFrame({"feature": feature_cols, "importance": importance})
    return out.sort_values("importance", ascending=False).reset_index(drop=True)


def plot_feature_importance(importance_df: pd.DataFrame, title: str, out_path: Path, top_n: int = 25) -> None:
    top = importance_df.head(top_n).iloc[::-1]
    fig, ax = plt.subplots(figsize=(10, 8))
    ax.barh(top["feature"], top["importance"])
    ax.set_title(title)
    ax.set_xlabel("Importance")
    ax.grid(True, axis="x", alpha=0.3)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    print(f"[SAVED] {out_path}")


# ============================================================
# Training tasks
# ============================================================


def train_and_evaluate_split(
    task_name: str,
    target_col: str,
    split_name: str,
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    feature_cols: List[str],
    preferred_label_order: List[str],
    display_label_map: Dict[str, str],
    out_dir: Path,
    seed: int,
) -> Tuple[pd.DataFrame, Dict]:
    X_train = train_df[feature_cols].copy()
    y_train = train_df[target_col].copy()
    X_test = test_df[feature_cols].copy()
    y_test = test_df[target_col].copy()

    estimators = build_models(seed)
    all_metrics = []
    best_info: Dict = {
        "task_name": task_name,
        "target_col": target_col,
        "split_name": split_name,
        "best_model_name": None,
        "best_model": None,
        "best_macro_f1": -1.0,
        "feature_cols": feature_cols,
    }

    task_dir = out_dir / task_name
    task_dir.mkdir(parents=True, exist_ok=True)

    for name, estimator in estimators.items():
        scale = name == "logistic_regression"
        model = make_pipeline(estimator, feature_cols, scale=scale)
        print(f"\n[TRAIN] {task_name} / {split_name} / {name}")
        model.fit(X_train, y_train)

        metrics, report_df, cm, labels = evaluate_model(
            name,
            model,
            X_test,
            y_test,
            preferred_label_order,
        )
        metrics.update({
            "task": task_name,
            "target": target_col,
            "split": split_name,
            "feature_count": len(feature_cols),
            "train_samples": len(train_df),
            "test_samples": len(test_df),
        })
        all_metrics.append(metrics)

        print(
            f"[RESULT] {task_name}/{split_name}/{name}: "
            f"accuracy={metrics['accuracy']:.4f}, "
            f"macro_f1={metrics['macro_f1']:.4f}, "
            f"weighted_f1={metrics['weighted_f1']:.4f}"
        )

        safe_name = f"{split_name}_{name}"
        report_path = task_dir / f"classification_report_{safe_name}.csv"
        report_df.to_csv(report_path, index=False, encoding="utf-8-sig")
        print(f"[SAVED] {report_path}")

        plot_confusion_matrix(
            cm,
            labels,
            title=f"{task_name} - {split_name} - {name}",
            out_path=task_dir / f"confusion_matrix_{safe_name}.png",
            display_label_map=display_label_map,
        )

        imp_df = extract_feature_importance(model, feature_cols)
        if imp_df is not None:
            imp_path = task_dir / f"feature_importance_{safe_name}.csv"
            imp_df.to_csv(imp_path, index=False, encoding="utf-8-sig")
            print(f"[SAVED] {imp_path}")
            plot_feature_importance(
                imp_df,
                title=f"{task_name} feature importance - {split_name} - {name}",
                out_path=task_dir / f"feature_importance_{safe_name}.png",
            )

        if metrics["macro_f1"] > best_info["best_macro_f1"]:
            best_info.update({
                "best_model_name": name,
                "best_model": model,
                "best_macro_f1": metrics["macro_f1"],
            })

    if best_info["best_model"] is not None:
        model_path = task_dir / f"best_model_{split_name}_{best_info['best_model_name']}.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(
                {
                    "model": best_info["best_model"],
                    "task_name": task_name,
                    "target_col": target_col,
                    "feature_cols": feature_cols,
                    "best_model_name": best_info["best_model_name"],
                    "split": split_name,
                    "holdout_pn": HOLDOUT_PN if split_name.startswith("pn_holdout") else None,
                    "label_order": preferred_label_order,
                },
                f,
            )
        best_info["model_path"] = str(model_path)
        print(f"[SAVED] {model_path}")

    return pd.DataFrame(all_metrics), best_info


def run_training_task(
    df_raw: pd.DataFrame,
    task_name: str,
    target_col: str,
    feature_selector,
    preferred_label_order: List[str],
    display_label_map: Dict[str, str],
    out_dir: Path,
    seed: int,
) -> Tuple[pd.DataFrame, List[Dict]]:
    print("\n" + "=" * 72)
    print(f"TASK: {task_name}")
    print(f"Target column: {target_col}")

    df_task = clean_task_dataframe(df_raw, target_col=target_col, include_golden=INCLUDE_GOLDEN, seed=seed)
    if df_task.empty or df_task[target_col].nunique() < 2:
        print(f"[SKIP] {task_name}: fewer than 2 valid target classes.")
        return pd.DataFrame(), []

    feature_cols = select_feature_columns(df_task, feature_selector)
    df_task, feature_cols = convert_features_to_numeric(df_task, feature_cols)

    print(f"Rows             : {len(df_task):,}")
    print(f"Target classes   : {df_task[target_col].nunique():,}")
    print(f"Feature columns  : {len(feature_cols):,}")
    print("\nClass counts:")
    print(df_task[target_col].value_counts().to_string())
    print("\nPN counts:")
    print(df_task["PN_ID"].value_counts().sort_index().to_string())

    task_dir = out_dir / task_name
    task_dir.mkdir(parents=True, exist_ok=True)

    feature_df = summarize_feature_groups(feature_cols)
    feature_df.to_csv(task_dir / f"feature_columns_{task_name}.csv", index=False, encoding="utf-8-sig")
    df_task[target_col].value_counts().rename_axis(target_col).reset_index(name="count").to_csv(
        task_dir / f"class_counts_{task_name}.csv",
        index=False,
        encoding="utf-8-sig",
    )
    print("\nFeature group counts:")
    print(feature_df["group"].value_counts().to_string())
    print(f"[SAVED] {task_dir / f'feature_columns_{task_name}.csv'}")

    all_metrics: List[pd.DataFrame] = []
    best_infos: List[Dict] = []

    if RUN_RANDOM_SPLIT:
        train_df, test_df = random_split_dataframe(df_task, target_col=target_col, seed=seed)
        metrics_df, best = train_and_evaluate_split(
            task_name=task_name,
            target_col=target_col,
            split_name="random_split",
            train_df=train_df,
            test_df=test_df,
            feature_cols=feature_cols,
            preferred_label_order=preferred_label_order,
            display_label_map=display_label_map,
            out_dir=out_dir,
            seed=seed,
        )
        metrics_df.to_csv(task_dir / "random_split_metrics.csv", index=False, encoding="utf-8-sig")
        all_metrics.append(metrics_df)
        best_infos.append(best)

    if RUN_PN_HOLDOUT:
        if HOLDOUT_PN in set(df_task["PN_ID"]):
            try:
                train_df, test_df = pn_holdout_split_dataframe(df_task, target_col=target_col, holdout_pn=HOLDOUT_PN)
                metrics_df, best = train_and_evaluate_split(
                    task_name=task_name,
                    target_col=target_col,
                    split_name=f"pn_holdout_{HOLDOUT_PN}",
                    train_df=train_df,
                    test_df=test_df,
                    feature_cols=feature_cols,
                    preferred_label_order=preferred_label_order,
                    display_label_map=display_label_map,
                    out_dir=out_dir,
                    seed=seed,
                )
                metrics_df.to_csv(task_dir / "pn_holdout_metrics.csv", index=False, encoding="utf-8-sig")
                all_metrics.append(metrics_df)
                best_infos.append(best)
            except ValueError as exc:
                print(f"[WARN] PN holdout skipped for {task_name}: {exc}")
        else:
            print(f"[WARN] HOLDOUT_PN {HOLDOUT_PN} not found for {task_name}. Skipping PN holdout split.")

    combined = pd.concat(all_metrics, ignore_index=True) if all_metrics else pd.DataFrame()
    if not combined.empty:
        combined.to_csv(task_dir / f"all_metrics_{task_name}.csv", index=False, encoding="utf-8-sig")
        print(f"[SAVED] {task_dir / f'all_metrics_{task_name}.csv'}")

    return combined, best_infos


def choose_best_for_bundle(best_infos: List[Dict]) -> Optional[Dict]:
    if not best_infos:
        return None
    # Prefer PN holdout models when available; otherwise use best random split.
    holdout = [b for b in best_infos if str(b.get("split_name", "")).startswith("pn_holdout")]
    candidates = holdout if holdout else best_infos
    candidates = [b for b in candidates if b.get("best_model") is not None]
    if not candidates:
        return None
    return sorted(candidates, key=lambda x: x.get("best_macro_f1", -1.0), reverse=True)[0]


# ============================================================
# Main
# ============================================================


def main() -> None:
    dataset_dir = resolve_dataset_dir()
    out_dir = Path(OUTPUT_DIR) if OUTPUT_DIR else dataset_dir / "outputs" / "model_training_v3_two_stage"
    out_dir.mkdir(parents=True, exist_ok=True)

    print("=== SI Diagnostic Model Training V3 Two-Stage Direct Run ===")
    print(f"Dataset directory : {dataset_dir.resolve()}")
    print(f"Output folder     : {out_dir.resolve()}")
    print(f"Holdout PN        : {HOLDOUT_PN}")
    print(f"Include golden    : {INCLUDE_GOLDEN}")
    print(f"Stage2 filter     : {'stage1 non-normal only' if STAGE2_ONLY_STAGE1_NON_NORMAL else 'all non-golden cases'}")

    df_raw, source_desc = load_v3_dataframe(dataset_dir)
    print(f"Source            : {source_desc}")
    print(f"Raw rows          : {len(df_raw):,}")
    print(f"Raw columns       : {len(df_raw.columns):,}")

    # Save a quick column inventory for traceability.
    pd.DataFrame({"column": list(df_raw.columns)}).to_csv(
        out_dir / "input_columns_v3.csv",
        index=False,
        encoding="utf-8-sig",
    )

    all_metrics: List[pd.DataFrame] = []
    bundle: Dict[str, object] = {
        "version": "v3_two_stage",
        "dataset_dir": str(dataset_dir),
        "source": source_desc,
        "holdout_pn": HOLDOUT_PN,
        "stage1_models": {},
        "stage2_model": None,
    }

    # ----------------------------
    # Stage 1: deviation heads
    # ----------------------------
    for target_col in STAGE1_TARGETS:
        if target_col not in df_raw.columns:
            print(f"[WARN] Stage-1 target missing and skipped: {target_col}")
            continue

        task_name = target_col
        metrics_df, best_infos = run_training_task(
            df_raw=df_raw,
            task_name=task_name,
            target_col=target_col,
            feature_selector=is_stage1_feature_name,
            preferred_label_order=STAGE1_STATUS_ORDER,
            display_label_map=STAGE1_DISPLAY_LABELS,
            out_dir=out_dir,
            seed=SEED,
        )
        if not metrics_df.empty:
            all_metrics.append(metrics_df)
        best = choose_best_for_bundle(best_infos)
        if best is not None:
            bundle["stage1_models"][target_col] = {
                "model": best["best_model"],
                "feature_cols": best["feature_cols"],
                "best_model_name": best["best_model_name"],
                "best_macro_f1": best["best_macro_f1"],
                "split": best["split_name"],
                "target_col": target_col,
                "label_order": STAGE1_STATUS_ORDER,
            }

    # ----------------------------
    # Stage 2: root-cause model
    # ----------------------------
    df_stage2 = df_raw.copy()
    if STAGE2_ONLY_STAGE1_NON_NORMAL and "stage1_overall_status" in df_stage2.columns:
        df_stage2 = df_stage2[df_stage2["stage1_overall_status"].astype(str) != "normal"].copy()

    if "label" in df_stage2.columns:
        metrics_df, best_infos = run_training_task(
            df_raw=df_stage2,
            task_name="stage2_root_cause",
            target_col="label",
            feature_selector=is_stage2_feature_name,
            preferred_label_order=STAGE2_LABEL_ORDER,
            display_label_map=STAGE2_DISPLAY_LABELS,
            out_dir=out_dir,
            seed=SEED,
        )
        if not metrics_df.empty:
            all_metrics.append(metrics_df)
        best = choose_best_for_bundle(best_infos)
        if best is not None:
            bundle["stage2_model"] = {
                "model": best["best_model"],
                "feature_cols": best["feature_cols"],
                "best_model_name": best["best_model_name"],
                "best_macro_f1": best["best_macro_f1"],
                "split": best["split_name"],
                "target_col": "label",
                "label_order": STAGE2_LABEL_ORDER,
            }
    else:
        print("[WARN] Stage-2 target 'label' not found; Stage 2 skipped.")

    if all_metrics:
        combined = pd.concat(all_metrics, ignore_index=True)
        combined_path = out_dir / "all_metrics_v3_two_stage.csv"
        combined.to_csv(combined_path, index=False, encoding="utf-8-sig")
        print("\n=== Metrics summary ===")
        cols = ["task", "split", "model", "accuracy", "macro_f1", "weighted_f1", "test_samples", "feature_count"]
        existing = [c for c in cols if c in combined.columns]
        print(combined[existing].to_string(index=False))
        print(f"[SAVED] {combined_path}")

    bundle_path = out_dir / "two_stage_model_bundle.pkl"
    with open(bundle_path, "wb") as f:
        pickle.dump(bundle, f)
    print(f"[SAVED] {bundle_path}")

    print("\nDone. Review metrics CSV files, confusion matrices, feature importance, and best_model_*.pkl files.")
    print("Suggested first files to inspect:")
    print(f"  {out_dir / 'all_metrics_v3_two_stage.csv'}")
    print(f"  {out_dir / 'stage1_overall_status'}")
    print(f"  {out_dir / 'stage2_root_cause'}")


if __name__ == "__main__":
    main()
